pub mod bluesky;
pub mod dingtalk;
pub mod discord;
pub mod email;
pub mod feishu;
pub mod github;
pub mod google_chat;
pub mod irc;
pub mod line;
pub mod linkedin;
pub mod mastodon;
pub mod matrix;
pub mod mattermost;
pub mod nostr;
pub mod reddit;
pub mod rocketchat;
pub mod signal;
pub mod slack;
pub mod sms;
pub mod teams;
pub mod telegram;
pub mod twitch;
pub mod webchat;
pub mod whatsapp;
pub mod zulip;

pub use bluesky::BlueskyAdapter;
pub use dingtalk::DingTalkAdapter;
pub use discord::DiscordAdapter;
pub use email::{EmailAdapter, EmailConfig};
pub use feishu::FeishuAdapter;
pub use github::GitHubAdapter;
pub use google_chat::GoogleChatAdapter;
pub use irc::{IrcAdapter, IrcProtocolMessage, parse_irc_message};
pub use line::LineAdapter;
pub use linkedin::LinkedInAdapter;
pub use mastodon::MastodonAdapter;
pub use matrix::MatrixAdapter;
pub use mattermost::MattermostAdapter;
pub use nostr::{NostrAdapter, NostrEvent};
pub use reddit::RedditAdapter;
pub use rocketchat::{RocketChatAdapter, RocketChatAuth};
pub use signal::SignalAdapter;
pub use slack::SlackAdapter;
pub use sms::SmsAdapter;
pub use teams::TeamsAdapter;
pub use telegram::TelegramAdapter;
pub use twitch::TwitchAdapter;
pub use webchat::{WebChatAdapter, WebChatSession};
pub use whatsapp::WhatsAppAdapter;
pub use zulip::ZulipAdapter;
