//! Common types for the desktop automation system.
//!
//! These types are used by the `AutomationBackend` trait and all platform
//! implementations (macOS, Linux, Windows).

use serde::{Deserialize, Serialize};

/// Information about an on-screen window.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WindowInfo {
    /// Window title (may be empty for unnamed windows).
    pub title: String,
    /// Name of the application owning this window.
    pub app_name: String,
    /// Screen position (x, y) of the top-left corner.
    pub position: Option<(i32, i32)>,
    /// Window size (width, height) in pixels.
    pub size: Option<(u32, u32)>,
    /// Whether the window is currently minimized.
    pub is_minimized: bool,
}

/// A UI element discovered via the accessibility tree.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UiElement {
    /// Stable-ish identifier: "AppName:role:index" (e.g. "Messages:button:3").
    /// Generated by `find_ui_elements`, consumed by `click_element` etc.
    pub element_id: String,
    /// Accessibility role: "button", "text_field", "menu_item", "row", etc.
    pub role: String,
    /// Accessibility label (human-readable name), if available.
    pub label: Option<String>,
    /// Current value of the element, if applicable.
    pub value: Option<String>,
    /// Whether the element is enabled for interaction.
    pub enabled: bool,
}

/// Selector used to filter UI elements when querying the accessibility tree.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UiSelector {
    /// Filter by accessibility role (e.g. "button", "text field").
    pub role: Option<String>,
    /// Filter by accessibility label (substring match).
    pub label: Option<String>,
    /// Filter by current value.
    pub value: Option<String>,
}

/// Result of a screenshot capture.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScreenshotResult {
    /// Base64-encoded PNG image data.
    pub png_base64: String,
    /// Image width in pixels.
    pub width: u32,
    /// Image height in pixels.
    pub height: u32,
}

/// Result of an OCR (optical character recognition) operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OcrResult {
    /// Full extracted text.
    pub text: String,
    /// Individual text regions with positions and confidence.
    pub regions: Vec<OcrRegion>,
}

/// A single text region from OCR.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OcrRegion {
    /// The text recognized in this region.
    pub text: String,
    /// Bounding box: (x, y, width, height). None if position unavailable.
    pub bounds: Option<(i32, i32, u32, u32)>,
    /// Confidence score (0.0–1.0).
    pub confidence: f32,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_window_info_serde_roundtrip() {
        let info = WindowInfo {
            title: "My Window".to_string(),
            app_name: "Safari".to_string(),
            position: Some((100, 200)),
            size: Some((1920, 1080)),
            is_minimized: false,
        };
        let json = serde_json::to_string(&info).expect("serialize");
        let deser: WindowInfo = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(deser.title, "My Window");
        assert_eq!(deser.size, Some((1920, 1080)));
    }

    #[test]
    fn test_window_info_none_optionals() {
        let info = WindowInfo {
            title: String::new(),
            app_name: "Finder".to_string(),
            position: None,
            size: None,
            is_minimized: true,
        };
        let json = serde_json::to_string(&info).expect("serialize");
        let deser: WindowInfo = serde_json::from_str(&json).expect("deserialize");
        assert!(deser.position.is_none());
        assert!(deser.is_minimized);
    }

    #[test]
    fn test_ui_element_serde_roundtrip() {
        let elem = UiElement {
            element_id: "Safari:button:3".to_string(),
            role: "button".to_string(),
            label: Some("Close".to_string()),
            value: None,
            enabled: true,
        };
        let json = serde_json::to_string(&elem).expect("serialize");
        let deser: UiElement = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(deser.element_id, "Safari:button:3");
        assert_eq!(deser.role, "button");
        assert!(deser.enabled);
    }

    #[test]
    fn test_ui_selector_defaults() {
        let sel = UiSelector::default();
        assert!(sel.role.is_none());
        assert!(sel.label.is_none());
        assert!(sel.value.is_none());
    }

    #[test]
    fn test_screenshot_result_serde() {
        let result = ScreenshotResult {
            png_base64: "iVBORw0KGgo=".to_string(),
            width: 1920,
            height: 1080,
        };
        let json = serde_json::to_string(&result).expect("serialize");
        let deser: ScreenshotResult = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(deser.width, 1920);
        assert_eq!(deser.height, 1080);
    }

    #[test]
    fn test_ocr_result_serde() {
        let result = OcrResult {
            text: "Hello World".to_string(),
            regions: vec![OcrRegion {
                text: "Hello".to_string(),
                bounds: Some((10, 20, 50, 15)),
                confidence: 0.95,
            }],
        };
        let json = serde_json::to_string(&result).expect("serialize");
        let deser: OcrResult = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(deser.regions.len(), 1);
        assert!((deser.regions[0].confidence - 0.95).abs() < f32::EPSILON);
    }

    #[test]
    fn test_ocr_empty_regions() {
        let result = OcrResult {
            text: String::new(),
            regions: Vec::new(),
        };
        let json = serde_json::to_string(&result).expect("serialize");
        let deser: OcrResult = serde_json::from_str(&json).expect("deserialize");
        assert!(deser.text.is_empty());
        assert!(deser.regions.is_empty());
    }

    #[test]
    fn test_ocr_region_no_bounds() {
        let region = OcrRegion {
            text: "test".to_string(),
            bounds: None,
            confidence: 0.5,
        };
        let json = serde_json::to_string(&region).expect("serialize");
        let deser: OcrRegion = serde_json::from_str(&json).expect("deserialize");
        assert!(deser.bounds.is_none());
    }
}
